// --- APPLIES_TO: Process -> Part (196 Zeilen) ---
UNWIND [
{f:"PROC_MJF", t:"PART_CUSTOM_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_CUSTOM_CONTACT", role:"optional finishing"},
{f:"PROC_MJF", t:"PART_LARGE_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_LARGE_CONTACT", role:"optional finishing"},
{f:"PROC_MJF", t:"PART_ADAPTIVE_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_ADAPTIVE_CONTACT", role:"optional finishing"},
{f:"PROC_RUBBER", t:"PART_VACUUM_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_VACUUM_CONTACT", role:"optional finishing"},
{f:"PROC_CNC", t:"PART_MAGNET_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_MAGNET_CONTACT", role:"optional finishing"},
{f:"PROC_MJF", t:"PART_FLAT_PA12_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_FLAT_PA12_CONTACT", role:"optional finishing"},
{f:"PROC_MJF", t:"PART_PREC_PA12_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_PREC_PA12_CONTACT", role:"optional finishing"},
{f:"PROC_MJF", t:"PART_XL_PA12_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_XL_PA12_CONTACT", role:"optional finishing"},
{f:"PROC_FFF", t:"PART_FLAT_PETG_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_FLAT_PETG_CONTACT", role:"optional finishing"},
{f:"PROC_CNC", t:"PART_FLAT_AL_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_FLAT_AL_CONTACT", role:"optional finishing"},
{f:"PROC_CNC", t:"PART_PREC_POM_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_PREC_POM_CONTACT", role:"optional finishing"},
{f:"PROC_CNC", t:"PART_PREC_AL7075_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_PREC_AL7075_CONTACT", role:"optional finishing"},
{f:"PROC_FFF", t:"PART_XL_CFPA_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_XL_CFPA_CONTACT", role:"optional finishing"},
{f:"PROC_MJF", t:"PART_V_PA12_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_V_PA12_CONTACT", role:"optional finishing"},
{f:"PROC_FFF", t:"PART_V_PETG_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_V_PETG_CONTACT", role:"optional finishing"},
{f:"PROC_CNC", t:"PART_V_POM_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_V_POM_CONTACT", role:"optional finishing"},
{f:"PROC_CNC", t:"PART_V_AL_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_V_AL_CONTACT", role:"optional finishing"},
{f:"PROC_MJF", t:"PART_CONC_PA12_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_CONC_PA12_CONTACT", role:"optional finishing"},
{f:"PROC_CNC", t:"PART_CONC_POM_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_CONC_POM_CONTACT", role:"optional finishing"},
{f:"PROC_FFF", t:"PART_TPU_PAD_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_TPU_PAD_CONTACT", role:"optional finishing"},
{f:"PROC_SILCAST", t:"PART_SIL_PAD_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_SIL_PAD_CONTACT", role:"optional finishing"},
{f:"PROC_FFF", t:"PART_FINRAY_TPU_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_FINRAY_TPU_CONTACT", role:"optional finishing"},
{f:"PROC_FFF", t:"PART_FINRAY_TPE_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_FINRAY_TPE_CONTACT", role:"optional finishing"},
{f:"PROC_FFF", t:"PART_LONG_CFPA_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_LONG_CFPA_CONTACT", role:"optional finishing"},
{f:"PROC_CNC", t:"PART_LONG_AL_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_LONG_AL_CONTACT", role:"optional finishing"},
{f:"PROC_CNC", t:"PART_THIN_POM_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_THIN_POM_CONTACT", role:"optional finishing"},
{f:"PROC_LASER", t:"PART_THIN_STEEL_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_THIN_STEEL_CONTACT", role:"optional finishing"},
{f:"PROC_MJF", t:"PART_INTERNAL_PA12_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_INTERNAL_PA12_CONTACT", role:"optional finishing"},
{f:"PROC_CNC", t:"PART_INTERNAL_AL_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_INTERNAL_AL_CONTACT", role:"optional finishing"},
{f:"PROC_MJF", t:"PART_3FINGER_PA12_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_3FINGER_PA12_CONTACT", role:"optional finishing"},
{f:"PROC_SILCAST", t:"PART_SOFT_SIL_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_SOFT_SIL_CONTACT", role:"optional finishing"},
{f:"PROC_RUBBER", t:"PART_VAC_SMALL_NBR_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_VAC_SMALL_NBR_CONTACT", role:"optional finishing"},
{f:"PROC_SILCAST", t:"PART_VAC_LARGE_SIL_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_VAC_LARGE_SIL_CONTACT", role:"optional finishing"},
{f:"PROC_MJF", t:"PART_VAC_ARRAY_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_VAC_ARRAY_CONTACT", role:"optional finishing"},
{f:"PROC_CNC", t:"PART_MAG_SMALL_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_MAG_SMALL_CONTACT", role:"optional finishing"},
{f:"PROC_CNC", t:"PART_MAG_WIDE_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_MAG_WIDE_CONTACT", role:"optional finishing"},
{f:"PROC_OVERMOLD", t:"PART_HYBRID_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_HYBRID_CONTACT", role:"optional finishing"},
{f:"PROC_SCREW", t:"PART_CUSTOM_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_LARGE_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_ADAPTIVE_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_VACUUM_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_MAGNET_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_FLAT_PA12_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_PREC_PA12_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_XL_PA12_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_FLAT_PETG_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_FLAT_AL_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_PREC_POM_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_PREC_AL7075_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_XL_CFPA_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_V_PA12_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_V_PETG_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_V_POM_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_V_AL_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_CONC_PA12_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_CONC_POM_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_TPU_PAD_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_SIL_PAD_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_FINRAY_TPU_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_FINRAY_TPE_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_LONG_CFPA_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_LONG_AL_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_THIN_POM_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_THIN_STEEL_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_INTERNAL_PA12_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_INTERNAL_AL_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_3FINGER_PA12_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_SOFT_SIL_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_VAC_SMALL_NBR_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_VAC_LARGE_SIL_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_VAC_ARRAY_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_MAG_SMALL_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_MAG_WIDE_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_HYBRID_CONTACT", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_CUSTOM_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_LARGE_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_ADAPTIVE_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_VACUUM_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_MAGNET_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_FLAT_PA12_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_PREC_PA12_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_XL_PA12_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_FLAT_PETG_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_FLAT_AL_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_PREC_POM_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_PREC_AL7075_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_XL_CFPA_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_V_PA12_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_V_PETG_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_V_POM_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_V_AL_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_CONC_PA12_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_CONC_POM_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_TPU_PAD_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_SIL_PAD_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_FINRAY_TPU_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_FINRAY_TPE_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_LONG_CFPA_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_LONG_AL_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_THIN_POM_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_THIN_STEEL_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_INTERNAL_PA12_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_INTERNAL_AL_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_3FINGER_PA12_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_SOFT_SIL_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_VAC_SMALL_NBR_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_VAC_LARGE_SIL_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_VAC_ARRAY_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_MAG_SMALL_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_MAG_WIDE_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_SCREW", t:"PART_HYBRID_INTERFACE", role:"reversible fastening (contact to interface)"},
{f:"PROC_REPAIR", t:"PART_CUSTOM_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_LARGE_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_ADAPTIVE_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_VACUUM_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_MAGNET_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_FLAT_PA12_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_PREC_PA12_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_XL_PA12_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_FLAT_PETG_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_FLAT_AL_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_PREC_POM_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_PREC_AL7075_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_XL_CFPA_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_V_PA12_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_V_PETG_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_V_POM_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_V_AL_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_CONC_PA12_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_CONC_POM_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_TPU_PAD_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_SIL_PAD_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_FINRAY_TPU_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_FINRAY_TPE_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_LONG_CFPA_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_LONG_AL_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_THIN_POM_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_THIN_STEEL_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_INTERNAL_PA12_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_INTERNAL_AL_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_3FINGER_PA12_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_SOFT_SIL_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_VAC_SMALL_NBR_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_VAC_LARGE_SIL_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_VAC_ARRAY_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_MAG_SMALL_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_MAG_WIDE_CONTACT", role:"replaceable wear part"},
{f:"PROC_REPAIR", t:"PART_HYBRID_CONTACT", role:"replaceable wear part"},
{f:"PROC_FFF", t:"PART_FLAT_ABS_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_FLAT_ABS_CONTACT", role:"optional finishing"},
{f:"PROC_FFF", t:"PART_FLAT_ASA_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_FLAT_ASA_CONTACT", role:"optional finishing"},
{f:"PROC_FFF", t:"PART_FLAT_PLA_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_FLAT_PLA_CONTACT", role:"optional finishing"},
{f:"PROC_SLS", t:"PART_PREC_PA11_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_PREC_PA11_CONTACT", role:"optional finishing"},
{f:"PROC_CNC", t:"PART_PREC_PC_CONTACT", role:"manufactures contact element"},
{f:"PROC_FINISH", t:"PART_PREC_PC_CONTACT", role:"optional finishing"},
{f:"PROC_RUBBER", t:"PART_PU_PAD_CONTACT", role:"manufactures contact element"}
] AS row
MATCH (source:Process {id: row.f})
MATCH (target:Part {id: row.t})
MERGE (source)-[r:APPLIES_TO]->(target)
SET r.role = row.role;

// --- APPLIES_TO: Process -> Material (23 Zeilen) ---
UNWIND [
{f:"PROC_ALU_EXTRUSION_IDEMAT", t:"MAT_ALU_GENERIC", role:"produces material"},
{f:"PROC_ALU_SHEET_IDEMAT", t:"MAT_ALU_GENERIC", role:"produces material"},
{f:"PROC_STEEL_SECTIONS_ILCD", t:"MAT_STEEL_GENERIC", role:"produces material"},
{f:"PROC_STEEL_HRC", t:"MAT_STEEL_GENERIC", role:"produces material"},
{f:"PROC_COPPER_WIRE_CONSMIX", t:"MAT_COPPER_GENERIC", role:"produces material"},
{f:"PROC_LEAD_SHEET_SECONDARY", t:"MAT_LEAD_GENERIC", role:"produces material"},
{f:"PROC_COPPER_SHEET_MARKETMIX", t:"MAT_COPPER_GENERIC", role:"produces material"},
{f:"PROC_LEAD_PRIMSEC_MIX", t:"MAT_LEAD_GENERIC", role:"produces material"},
{f:"PROC_COPPER_SHEET_CONSMIX", t:"MAT_COPPER_GENERIC", role:"produces material"},
{f:"PROC_STEEL_REBAR", t:"MAT_STEEL_GENERIC", role:"produces material"},
{f:"PROC_STEEL_GALV_ILCD", t:"MAT_STEEL_GENERIC", role:"produces material"},
{f:"PROC_COPPER_TUBE_MARKETMIX", t:"MAT_COPPER_GENERIC", role:"produces material"},
{f:"PROC_STEEL_GALV_RECYCLED", t:"MAT_STEEL_GENERIC", role:"produces material"},
{f:"PROC_COPPER_WIRE_MARKETMIX", t:"MAT_COPPER_GENERIC", role:"produces material"},
{f:"PROC_STEEL_SECTIONS_RECYCLED", t:"MAT_STEEL_GENERIC", role:"produces material"},
{f:"PROC_COPPER_TUBE_CONSMIX", t:"MAT_COPPER_GENERIC", role:"produces material"},
{f:"PROC_STEEL_TINPLATE", t:"MAT_STEEL_GENERIC", role:"produces material"},
{f:"PROC_STEEL_HRC_RECYCLED", t:"MAT_STEEL_GENERIC", role:"produces material"},
{f:"PROC_STEEL_HRC_ILCD", t:"MAT_STEEL_GENERIC", role:"produces material"},
{f:"PROC_STEEL_HR_SECTION", t:"MAT_STEEL_GENERIC", role:"produces material"},
{f:"PROC_ZINC_PRIMARY", t:"MAT_ZINC_GENERIC", role:"produces material"},
{f:"PROC_LEAD_PRIMARY", t:"MAT_LEAD_GENERIC", role:"produces material"},
{f:"PROC_ALU_EXTRUSION_EF", t:"MAT_ALU_GENERIC", role:"produces material"}
] AS row
MATCH (source:Process {id: row.f})
MATCH (target:Material {id: row.t})
MERGE (source)-[r:APPLIES_TO]->(target)
SET r.role = row.role;

// --- EVALUATES_CRITERION: DataQuality -> DataQualityCriterion (23 Zeilen) ---
UNWIND [
{f:"DQ_MANUF", t:"DQC_TEMP", score:5.0, rating:"very good"},
{f:"DQ_MANUF", t:"DQC_ACC", score:5.0, rating:"very good"},
{f:"DQ_MANUF", t:"DQC_COMP", score:4.0, rating:"good"},
{f:"DQ_MANUF", t:"DQC_CONS", score:5.0, rating:"very good"},
{f:"DQ_MANUF", t:"DQC_COMPAB", score:4.0, rating:"good"},
{f:"DQ_MANUAL", t:"DQC_TEMP", score:3.0, rating:"medium"},
{f:"DQ_MANUAL", t:"DQC_ACC", score:4.0, rating:"good"},
{f:"DQ_MANUAL", t:"DQC_COMP", score:4.0, rating:"good"},
{f:"DQ_MANUAL", t:"DQC_CONS", score:4.0, rating:"good"},
{f:"DQ_MANUAL", t:"DQC_COMPAB", score:3.0, rating:"medium"},
{f:"DQ_RESELLER", t:"DQC_TEMP", score:4.0, rating:"good"},
{f:"DQ_RESELLER", t:"DQC_ACC", score:3.0, rating:"medium"},
{f:"DQ_RESELLER", t:"DQC_COMP", score:3.0, rating:"medium"},
{f:"DQ_RESELLER", t:"DQC_CONS", score:3.0, rating:"medium"},
{f:"DQ_RESELLER", t:"DQC_COMPAB", score:3.0, rating:"medium"},
{f:"DQ_CONCEPT", t:"DQC_TEMP", score:5.0, rating:"very good"},
{f:"DQ_CONCEPT", t:"DQC_ACC", score:2.0, rating:"low"},
{f:"DQ_CONCEPT", t:"DQC_COMP", score:2.0, rating:"low"},
{f:"DQ_CONCEPT", t:"DQC_CONS", score:3.0, rating:"medium"},
{f:"DQ_CONCEPT", t:"DQC_COMPAB", score:4.0, rating:"good"},
{f:"DQ_CONCEPT", t:"DQC_UNC", score:2.0, rating:"low"},
{f:"DQ_SCREW_JOIN", t:"DQC_ACC", score:4.0, rating:"good"},
{f:"DQ_SCREW_JOIN", t:"DQC_COMP", score:3.0, rating:"fair (not yet verified per artifact)"}
] AS row
MATCH (source:DataQuality {id: row.f})
MATCH (target:DataQualityCriterion {id: row.t})
MERGE (source)-[r:EVALUATES_CRITERION]->(target)
SET r.score = row.score, r.rating = row.rating;
